import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import Image from 'next/image'
import axios from 'axios';

const Home: NextPage = ({ allPostsData }: any) => {
  console.log({ allPostsData });

  const myLoader = ({ src, width, quality }: any) => {
    return `${src}?w=${width}&q=${quality || 25}`
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>My first app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h2>Root menu</h2>
        <Link href={"/product"}>
          Product
        </Link> &nbsp;

        <Link href={"/history/2"}>
          History
        </Link> &nbsp;

        <Link href={"/blog"}>
          Blog
        </Link> &nbsp;
      </div>

      <Image
        src="/images/MercedesLogo.jpg" // Route of the image file
        height={144} // Desired size with correct aspect ratio
        width={144} // Desired size with correct aspect ratio
        alt="Your Name"
      // layout='responsive'
      />


      <Image
        loader={myLoader}
        src="/images/loading.gif"
        alt="Picture of the author"
        width={100}
        height={100}
        priority={true}
      />
    </div>
  )
}

export default Home

export async function getSortedPostsData() {
  return await axios.get('http://covid19.richdataservices.com/rds/api/catalog')
}
export async function getStaticProps() {
  const response = await getSortedPostsData()
  return {
    props: {
      allPostsData: response?.data
    }
  }
}